In [15]:
import numpy as np
np_arr1 = np.arange(10)
np_arr2 = np.arange(10)
np_arr1 + np_arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np_arr1 * np_arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [39]:
random_array = np.random.randint(0, 100, size=(100)) 

In [28]:
print(random_array)

[81 11 48 11 41 72 97 14 71 59 87 58 61 81 24 82 94  1 94 81 97 78  8 53
 28 67 66 74 13 64 29 74 23 53 11 75 99  0 59 41 41 91 88 69 82 47 38 75
 18 72 19 15 22 18 73 90 82 37 23 23 91 41 25 98  1 14  4 49 25 16 62 40
 62 18 26 97 11 68 16 66 64 66 26  4 31 27  4 31  8 71 96 19 99 48 36 18
 61 38 65 65]


In [29]:
random_array.shape

(100,)

In [30]:
random_array.size

100

In [33]:
random_array.dtype

dtype('int32')

In [34]:
random_array[:10]

array([81, 11, 48, 11, 41, 72, 97, 14, 71, 59])

In [35]:
random_array * random_array

array([6561,  121, 2304,  121, 1681, 5184, 9409,  196, 5041, 3481, 7569,
       3364, 3721, 6561,  576, 6724, 8836,    1, 8836, 6561, 9409, 6084,
         64, 2809,  784, 4489, 4356, 5476,  169, 4096,  841, 5476,  529,
       2809,  121, 5625, 9801,    0, 3481, 1681, 1681, 8281, 7744, 4761,
       6724, 2209, 1444, 5625,  324, 5184,  361,  225,  484,  324, 5329,
       8100, 6724, 1369,  529,  529, 8281, 1681,  625, 9604,    1,  196,
         16, 2401,  625,  256, 3844, 1600, 3844,  324,  676, 9409,  121,
       4624,  256, 4356, 4096, 4356,  676,   16,  961,  729,   16,  961,
         64, 5041, 9216,  361, 9801, 2304, 1296,  324, 3721, 1444, 4225,
       4225])

In [41]:
np.sum(random_array)

5043

In [43]:
random_array

array([68, 84, 73, 61, 82, 29, 32, 47, 89,  8, 74, 93,  8, 10, 78, 97, 17,
       11, 27, 41,  0, 64, 68, 42, 27,  0, 67, 37, 35, 99, 10, 90, 31, 61,
       39, 71, 19, 90, 99, 57, 59, 66, 74, 76, 24,  3, 35, 24, 41, 38, 26,
       80, 85, 21, 91, 68, 91, 48, 46, 80, 48, 78,  2, 87, 48, 57,  0, 38,
       48, 62, 46, 91, 37, 49, 80, 59,  4, 42, 30, 28, 80, 84, 60, 31, 54,
       57,  8, 97, 38, 32, 19, 10,  0, 73, 34, 72, 88, 25, 60, 76])

In [42]:
np.sort(random_array)

array([ 0,  0,  0,  0,  2,  3,  4,  8,  8,  8, 10, 10, 10, 11, 17, 19, 19,
       21, 24, 24, 25, 26, 27, 27, 28, 29, 30, 31, 31, 32, 32, 34, 35, 35,
       37, 37, 38, 38, 38, 39, 41, 41, 42, 42, 46, 46, 47, 48, 48, 48, 48,
       49, 54, 57, 57, 57, 59, 59, 60, 60, 61, 61, 62, 64, 66, 67, 68, 68,
       68, 71, 72, 73, 73, 74, 74, 76, 76, 78, 78, 80, 80, 80, 80, 82, 84,
       84, 85, 87, 88, 89, 90, 90, 91, 91, 91, 93, 97, 97, 99, 99])

In [46]:
random_array2 = np.random.randint(0, 100, size=(100,3)) 

In [48]:
random_array2.shape

(100, 3)

In [49]:
random_array2[:,1]

array([44,  1, 26, 62, 43, 38,  1, 15, 50, 20, 96, 72, 94, 73, 50, 53, 81,
       32, 68, 44, 60, 61, 44, 16, 64, 74, 43, 53, 36, 61, 80, 90, 15, 56,
       24, 74, 98, 59, 86, 28, 19, 83, 94, 64, 51, 28, 94, 56, 91, 63, 51,
       77, 75, 55, 60, 86,  7, 29, 25, 29, 19, 74, 90, 48, 87,  8, 62, 19,
       37, 93, 72, 21, 55, 73, 37, 27,  8, 27, 10, 73, 74, 99, 72, 83, 46,
       14, 65, 41, 74,  5,  5, 52, 12, 29, 98, 48, 59, 43, 18, 38])

In [50]:
random_array2[:,2]

array([66, 36,  9, 99, 10, 26, 25, 63, 38, 40, 98, 96, 37,  3, 79, 20, 22,
       75, 69, 38, 53,  3, 80, 29, 79, 74,  6, 19, 85, 61, 76, 51,  9, 13,
       46, 92, 20, 11,  9, 25, 61, 60, 40, 40, 51, 64, 36, 91, 79, 59, 51,
       33, 39, 34,  4, 43, 48, 36,  3, 18, 58, 62,  1, 18,  4, 40, 51, 55,
       73,  7,  2,  7, 46, 40, 73, 87,  7, 61, 77, 34, 40, 76, 68, 42, 57,
       21, 57,  3, 23, 28, 45, 91, 67, 55, 14, 84, 69, 10, 48, 79])

In [51]:
random_array2[:,0]

array([87,  6, 98,  5, 93, 61, 87, 15, 59, 63, 36, 18, 55, 77, 16, 35, 15,
       52, 53, 34, 69, 58, 71, 21, 51, 42, 37, 84, 87, 40, 38, 53, 20, 18,
        7, 37, 85, 97, 46, 31, 51, 36, 51, 65, 18, 57, 61, 91, 93, 95, 16,
       30, 73,  5, 11,  0,  4, 38, 58, 92, 91, 33,  3, 68, 42, 86, 87, 37,
       71, 30, 27, 84, 60,  2, 86,  0, 25, 26, 77, 99, 85, 37,  7, 13, 96,
       15, 45, 70, 44, 52, 68, 46, 98, 82, 27, 63, 64, 12, 50, 21])

In [53]:
random_array2[:10,2]

array([66, 36,  9, 99, 10, 26, 25, 63, 38, 40])

In [55]:
import pandas as pd

In [57]:
movies = pd.read_csv('top movies.csv')

In [59]:
movies.head()

id                     title original_language release_date  vote_average  \
0  278  The Shawshank Redemption                en   1994-09-23         8.706   
1  238             The Godfather                en   1972-03-14         8.690   
2  240     The Godfather Part II                en   1974-12-20         8.575   
3  424          Schindler's List                en   1993-12-15         8.565   
4  389              12 Angry Men                en   1957-04-10         8.546   

   vote_count  popularity                                           overview  \
0       26840     150.307  Imprisoned in the 1940s for the double murder ...   
1       20373     122.973  Spanning the years 1945 to 1955, a chronicle o...   
2       12291      94.204  In the continuing saga of the Corleone crime f...   
3       15695      74.615  The true story of how businessman Oskar Schind...   
4        8522      54.678  The defense and the prosecution have rested an...   

         genre_ids                       Genres  
0         [18, 80]           ['Drama', 'Crime']  
1         [18, 80]           ['Drama', 'Crime']  
2         [18, 80]           ['Drama', 'Crime']  
3  [18, 36, 10752]  ['Drama', 'History', 'War']  
4             [18]                    ['Drama']

In [60]:
movies.shape

(9630, 10)

In [63]:
movies.iloc[0]

id                                                                 278
title                                         The Shawshank Redemption
original_language                                                   en
release_date                                                1994-09-23
vote_average                                                     8.706
vote_count                                                       26840
popularity                                                     150.307
overview             Imprisoned in the 1940s for the double murder ...
genre_ids                                                     [18, 80]
Genres                                              ['Drama', 'Crime']
Name: 0, dtype: object

In [65]:
movies['title']

0         The Shawshank Redemption
1                    The Godfather
2            The Godfather Part II
3                 Schindler's List
4                     12 Angry Men
                   ...            
9625             Alone in the Dark
9626                Disaster Movie
9627             House of the Dead
9628          Dragonball Evolution
9629    Birdemic: Shock and Terror
Name: title, Length: 9630, dtype: object

In [66]:
movies['original_language'].unique()

array(['en', 'ja', 'hi', 'ko', 'es', 'it', 'fr', 'pt', 'zh', 'tr', 'ru',
       'sv', 'ar', 'de', 'cn', 'da', 'bn', 'fa', 'th', 'hu', 'pl', 'te',
       'sr', 'nl', 'sh', 'et', 'uk', 'id', 'cs', 'gl', 'ro', 'ga', 'no',
       'bs', 'el', 'fi', 'is', 'ml', 'la', 'tn', 'he', 'km', 'eu', 'hy',
       'lt'], dtype=object)

In [70]:
english_movies = movies[movies['original_language'] =='en']

In [72]:
english_movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7640 entries, 0 to 9629
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 7640 non-null   int64  
 1   title              7640 non-null   object 
 2   original_language  7640 non-null   object 
 3   release_date       7640 non-null   object 
 4   vote_average       7640 non-null   float64
 5   vote_count         7640 non-null   int64  
 6   popularity         7640 non-null   float64
 7   overview           7640 non-null   object 
 8   genre_ids          7640 non-null   object 
 9   Genres             7640 non-null   object 
dtypes: float64(2), int64(2), object(6)
memory usage: 656.6+ KB


In [74]:
english_movies.to_csv('eng movies.csv')

In [89]:
english_movies[english_movies['Genres'].apply(lambda x: 'Animation' in x and 'Drama' in x)]

id                                    title original_language  \
36    704264                Primal: Tales of Savagery                en   
87      8587                            The Lion King                en   
204   555604           Guillermo del Toro's Pinocchio                en   
288   339877                           Loving Vincent                en   
328   574074                                  Kitbull                en   
400   150540                               Inside Out                en   
502   435129                          The Breadwinner                en   
516   293299                                    Feast                en   
529   303867                        World of Tomorrow                en   
549   779047                                 Us Again                en   
726   486589           Red Shoes and the Seven Dwarfs                en   
782     9023         Spirit: Stallion of the Cimarron                en   
786   713776           If Anything Happens I Love You                en   
1355    9081                              Waking Life                en   
1361    9081                              Waking Life                en   
1391   14919             Batman: Mask of the Phantasm                en   
1566  487670                    The Death of Superman                en   
1624   37135                                   Tarzan                en   
2092    9837                      The Prince of Egypt                en   
2441   11837                           Watership Down                en   
2656   10948                    The Fox and the Hound                en   
2755   10545              The Hunchback of Notre Dame                en   
2757  291270                                Anomalisa                en   
2767  420818                            The Lion King                en   
3158  926899                                The House                en   
3183    3170                                    Bambi                en   
3330   11848                              Animal Farm                en   
3486  116440  Maggie Simpson in "The Longest Daycare"                en   
3934   18937                        Quest for Camelot                en   
4268   15171                          Charlotte's Web                en   
4329   51052                         Arthur Christmas                en   
4331   11497                    All Dogs Go to Heaven                en   
4534    4978                         An American Tail                en   
4896   65291           Green Lantern: Emerald Knights                en   
5131  382322                 Batman: The Killing Joke                en   
5446   13205                                 Bambi II                en   
6138  152795                             The Congress                en   
7174   12593                            Fritz the Cat                en   
8778    9513          Garfield: A Tail of Two Kitties                en   

     release_date  vote_average  vote_count  popularity  \
36     2019-11-21         8.395         311      14.896   
87     1994-06-24         8.257       18081     131.119   
204    2022-11-09         8.095        2853      36.367   
288    2017-06-22         8.004        2417      16.001   
328    2019-01-18         7.967         363      29.134   
400    2015-06-17         7.914       21669     231.491   
502    2017-11-17         7.800         818      11.099   
516    2014-10-25         7.841         838       7.906   
529    2015-01-22         7.830         314       6.341   
549    2021-03-03         7.800         311      23.821   
726    2019-07-25         7.725        1071      35.423   
782    2002-05-24         7.696        4511      67.378   
786    2020-03-07         7.694         872       6.470   
1355   2001-10-19         7.479         856      12.296   
1361   2001-10-19         7.479         856      12.296   
1391   1993-12-25         7.500        1077      33.666   
1566  

In [76]:
english_movies['Genres']

0                                      ['Drama', 'Crime']
1                                      ['Drama', 'Crime']
2                                      ['Drama', 'Crime']
3                             ['Drama', 'History', 'War']
4                                               ['Drama']
                              ...                        
9625                      ['Action', 'Fantasy', 'Horror']
9626                                           ['Comedy']
9627                     ['Horror', 'Action', 'Thriller']
9628    ['Action', 'Adventure', 'Fantasy', 'Science Fi...
9629                    ['Romance', 'Horror', 'Thriller']
Name: Genres, Length: 7640, dtype: object